### ISSUE TITLE
Add main menu, option to use http requests/api to send messages

### ISSUE THREAD

**Issue by IamMU** [mrpandya/whatsapp-bomber#19]
Option to use API is only an option, the actual functionality will is not under scope of this issue.

**Comment by IamMU** [comment]
![image](https://user-images.githubusercontent.com/100090152/193810732-8c59ddeb-32bc-4bc8-8769-0b5df52a74b3.png)
![image](https://user-images.githubusercontent.com/100090152/193810840-56db0ac4-cee7-406c-9389-d2d2a95328b1.png)
Current idea/progress

**Comment by jamalmohamedcollege770** [comment]
WhatsApp bomber

**Comment by jamalmohamedcollege770** [comment]
WhatsApp bomber
