### ISSUE TITLE
Add search contact feature

### ISSUE THREAD

**Issue by mrpandya** [mrpandya/whatsapp-bomber#6]
Add the search contact feature before selecting the contact

**Comment by IamMU** [comment]
I am free to add the feature in a few hours(~2)

**Comment by mrpandya** [comment]
sure go ahead

**Comment by IamMU** [comment]
I need some information about if the user get an option to search the contact? Or do we do it like this: Send messages to all contacts, and the contacts at that couldn't be selected are done via searching them and then sending a message?

**Comment by mrpandya** [comment]
the latter one, currently the bot checks only the ones present on the screen, and thus to avoid the crash if then contact isn't present on the screen, we need this feature which will make use of the search bar and bring the contact/group name to the top and then the bot can proceed to send the message.

**Comment by IamMU** [comment]
Ok understood
